### ISSUE TITLE
Support for Symfony4.x 

### ISSUE THREAD

**Issue by darthf1** [voryx/ThruwayBundle#71]
Is it planned to support SF4.0 in the near future?

**Comment by darthf1** [comment]
If i install the package in SF4.0 with Voryx/Thruway 0.5.1 I get:

```
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Voryx\ThruwayBundle\VoryxThruwayBundle::__construct(), 0 passed in D:\www\websocket\src\Kernel.php on line 32 and exactly 1 expected in D:\www\websocket\vendor\voryx\thruway-bundle\src\Voryx\ThruwayBundle\VoryxThruwayBundle.php:27
!!  Stack trace:
!!  #0 D:\www\websocket\src\Kernel.php(32): Voryx\ThruwayBundle\VoryxThruwayBundle->__construct()
!!  #1 D:\www\websocket\vendor\symfony\http-kernel\Kernel.php(403): App\Kernel->registerBundles()
!!  #2 D:\www\websocket\vendor\symfony\http-kernel\Kernel.php(122): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #3 D:\www\websocket\vendor\symfony\framework-bundle\Console\Application.php(63): Symfony\Component\HttpKernel\Kernel->boot()
!!  #4 D:\www\websocket\vendor\symfony\console\Application.php(143): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 D:\www\ in D:\www\websocket\vendor\voryx\thruway-bundle\src\Voryx\ThruwayBundle\VoryxThruwayBundle.php on line 27
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Voryx\ThruwayBundle\VoryxThruwayBundle::__construct(), 0 passed in D:\www\websocket\src\Kernel.php on line 32 and exactly 1 expected in D:\www\websocket\vendor\voryx\thruway-bundle\src\Voryx\ThruwayBundle\VoryxThruwayBundle.php:27
!!  Stack trace:
!!  #0 D:\www\websocket\src\Kernel.php(32): Voryx\ThruwayBundle\VoryxThruwayBundle->__construct()
!!  #1 D:\www\websocket\vendor\symfony\http-kernel\Kernel.php(403): App\Kernel->registerBundles()
!!  #2 D:\www\websocket\vendor\symfony\http-kernel\Kernel.php(122): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #3 D:\www\websocket\vendor\symfony\framework-bundle\Console\Application.php(63): Symfony\Component\HttpKernel\Kernel->boot()
!!  #4 D:\www\websocket\vendor\symfony\console\Application.php(143): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 D:\www\ in D:\www\websocket\vendor\voryx\thruway-bundle\src\Voryx\ThruwayBundle\VoryxThruwayBundle.php on line 27
!!
```

**Comment by davidwdan** [comment]
I have no plans to support SF4.0 anytime soon.

**Comment by davidwdan** [comment]
If you want to test it out, the dev-master branch now supports symfony 4.
